[default.limits]
json = "50 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[default]
address = "0.0.0.0"
port = 8008
workers = 1
max_blocking = 512
keep_alive = 5
ident = "callback-test-app"
log_level = "debug"
temp_dir = "/tmp"
cli_colors = true
